services:
  simulator-publisher:
    container_name: simulator-publisher
    build:
      context: .
      dockerfile: Dockerfile
    image: hedera-block-simulator:latest
    networks:
      - block-node_default
    env_file:
      - .env
    environment:
      - BLOCK_STREAM_SIMULATOR_MODE=${PUBLISHER_BLOCK_STREAM_SIMULATOR_MODE}
      - PROMETHEUS_ENDPOINT_PORT_NUMBER=${PUBLISHER_PROMETHEUS_ENDPOINT_PORT_NUMBER}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9998/metrics"]
      interval: 3s
      timeout: 10s
      retries: 5
    volumes:
      - simulator_data:/opt/simulator/data

  simulator-consumer:
    container_name: simulator-consumer
    build:
      context: .
      dockerfile: Dockerfile
    image: hedera-block-simulator:latest
    networks:
      - block-node_default
    env_file:
      - .env
    environment:
      - BLOCK_STREAM_SIMULATOR_MODE=${CONSUMER_BLOCK_STREAM_SIMULATOR_MODE}
      - PROMETHEUS_ENDPOINT_PORT_NUMBER=${CONSUMER_PROMETHEUS_ENDPOINT_PORT_NUMBER}
    depends_on:
      simulator-publisher:
        condition: service_healthy

  prometheus:
   image: prom/prometheus
   container_name: prometheus
   networks:
     - block-node_default
   volumes:
     - ./metrics/prometheus.yml:/etc/prometheus.yml
   command:
     - '--config.file=/etc/prometheus/prometheus.yml'
   ports:
     - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - block-node_default
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_DISABLE_SIGNOUT_MENU: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
    volumes:
      - ./metrics/dashboards:/etc/grafana/provisioning/dashboards
      - ./metrics/datasources/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    ports:
      - "3000:3000"

networks:
  block-node_default:
    name: block-node_default
    external: true

volumes:
  simulator_data:
